## Feature Selection Assigment


---

The focus of this task is to work with the preprocessed data set in the previous **Preprocessing assigment**.These topics are addressed in this notebook.


*   **Part 1**: PCA on the preprocessed data
*  **Part 2**: Inconsistency Rate on preprocessed data

Before we begin we must address some issues that is present the in the preprocessed data and resolve them. The preprocessed data has a lot of interpolated datas which will actually create a problem during the feature selection as well as in the later parts. So we will filter out the datas by the range of the datas in the main station.

time series range for station a: 2007-09-01 00:00:00 to 2017-12-31 23:00:00

time series range for station b: 2000-01-01 00:00:00 to 2017-12-31 23:00:00

time series range for station c: 2003-06-26 15:00:00 to 2017-12-31 23:00:00

time series range for station main: 2014-01-01 01:00:00 to 2017-12-31 23:00:00

We will take the date range **2014-01-01 01:00:00 to 2017-12-31 23:00:00** so that we don't have to deal with the interpolated datas.

In [1]:
import pandas as pd
import math
import numpy as np
from sklearn.decomposition import PCA

In [32]:
df_prep = pd.read_csv('pca_data.csv')
df_prep.drop(['Unnamed: 0'], axis=1,inplace=True)
df_prep

,PC-1,PC-2,PC-3,PC-4,PC-5,PC-6,PC-7,PC-8,PC-9,water_level
0,-0.483659,2.788656,-0.873400,0.168075,-0.307278,-0.059797,0.001902,-0.006596,0.001041,0.049463
1,-0.523836,2.818949,-0.880233,0.168626,-0.448422,-0.010759,0.007169,-0.006510,0.000426,0.049463
2,0.335936,3.032178,0.954340,0.119193,-0.290623,-0.005231,0.003620,0.000420,-0.000217,0.049463
3,0.322376,3.049963,0.977805,0.121684,-0.118240,0.002769,0.004526,0.000280,-0.000291,0.049463
4,0.302442,3.064295,0.971895,0.120828,-0.209430,-0.005879,0.003654,0.000396,-0.000194,0.049463
...,...,...,...,...,...,...,...,...,...,...
35059,-2.240596,-1.422644,-0.564749,0.155168,-0.577738,-0.004765,-0.009687,-0.009932,-0.004102,4.198110
35060,-1.919499,-0.837928,-0.833578,-0.550105,-0.730959,-0.011078,-0.019943,-0.009959,-0.000560,4.425433
35061,-1.891474,-1.253328,0.344196,0.128944,-0.735002,-0.022360,-0.023797,-0.005906,-0.002139,4.652756
35062,-1.565873,-0.668332,0.089789,-0.574102,-0.757276,0.004797,0.003563,-0.006648,0.009708,4.936910
35063,-1.999479,-1.159018,0.371391,0.132034,-0.726719,0.008920,0.051503,-0.006753,0.032724,5.164234

In [72]:
def updateDataFrameToOrdinalValues (dataFrame,column,labels):
    max = math.ceil(dataFrame[column].max()) + 1
    min = math.floor(dataFrame[column].min()) - 1
    print(column, 'min',min, 'max',max)
    ranges = np.arange(min,max,((abs(min)+abs(max))/(len(labels)+1)))
    print(column,ranges)
    rep_vals = []
    i=0
    while i < len(ranges)-1:
        dataFrame[column] = np.where((dataFrame[column]>ranges[i]) & (dataFrame[column]<ranges[i+1]), int(max+i), dataFrame[column])
        rep_vals.append((max+i))
        i += 1
    dataFrame[column].replace(rep_vals,labels,inplace=True)

In [76]:
#water_levels = df_prep_filtered['level_cm'].to_numpy()

#newComponents['water_level'] = water_levels

#Update data to ordinalValues

labels = ['decreased','normal','increased']
newData = df_prep.copy(deep=True)
for i in newData.columns:
    updateDataFrameToOrdinalValues(newData,i,labels)
newData.head(10)

PC-1 min -6 max 8
PC-1 [-6.  -2.5  1.   4.5]
PC-2 min -5 max 6
PC-2 [-5.   -2.25  0.5   3.25]
PC-3 min -4 max 5
PC-3 [-4.   -1.75  0.5   2.75]
PC-4 min -4 max 4
PC-4 [-4. -2.  0.  2.]
PC-5 min -3 max 3
PC-5 [-3.  -1.5  0.   1.5]
PC-6 min -2 max 2
PC-6 [-2. -1.  0.  1.]
PC-7 min -2 max 4
PC-7 [-2.  -0.5  1.   2.5]
PC-8 min -2 max 3
PC-8 [-2.   -0.75  0.5   1.75]
PC-9 min -2 max 2
PC-9 [-2. -1.  0.  1.]
water_level min -4 max 12
water_level [-4.  0.  4.  8.]

,PC-1,PC-2,PC-3,PC-4,PC-5,PC-6,PC-7,PC-8,PC-9,water_level
0,normal,increased,normal,increased,normal,normal,normal,normal,increased,normal
1,normal,increased,normal,increased,normal,normal,normal,normal,increased,normal
2,normal,increased,increased,increased,normal,normal,normal,normal,normal,normal
3,normal,increased,increased,increased,normal,increased,normal,normal,normal,normal
4,normal,increased,increased,increased,normal,normal,normal,normal,normal,normal
5,normal,increased,normal,increased,normal,normal,normal,normal,increased,normal
6,normal,increased,normal,increased,normal,increased,normal,normal,increased,normal
7,normal,increased,increased,increased,normal,normal,normal,normal,increased,normal
8,normal,increased,normal,increased,normal,normal,normal,normal,increased,normal
9,normal,increased,increased,increased,normal,normal,normal,normal,normal,normal

In [86]:
components = ['PC-1','PC-2','PC-3','PC-4','PC-5','PC-6','PC-7','PC-8','PC-9']

def generate_IR():

    i = 0
    while i < len(components):
        uc = 0
        IZ = np.array([])
        class_traces = pd.DataFrame(data=None, index=None, columns=labels, dtype=None, copy=False)
        while uc < len(labels):
            trace = getOccurances(labels[uc],newData.to_numpy(),i)
            class_traces.loc[uc] = trace
            max_val = np.amax(trace)
            iz_score = np.sum(trace) - max_val
            IZ = np.append(IZ,iz_score)
            uc +=1
        
        class_traces['IZ'] = IZ
        IR = computeIR(class_traces)
        feature_ir[components [i]] = [IR]
        print(class_traces)
        i += 1
        
generate_IR()

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0     1660.0  1174.0      276.0  1450.0
1    14022.0  5420.0     1362.0  6782.0
2     9275.0  1094.0      152.0  1246.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0      636.0    73.0       13.0    86.0
1    17132.0  4479.0     1002.0  5481.0
2     7201.0  3071.0      772.0  3843.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0     1068.0   246.0       40.0   286.0
1    17131.0  4888.0     1021.0  5909.0
2     6996.0  2540.0      725.0  3265.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0       66.0     3.0        2.0     5.0
1     5076.0  1444.0      337.0  1781.0
2    20079.0  6242.0     1451.0  7693.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0       26.0    18.0        0.0    18.0
1    11831.0  4383.0      867.0  5250.0
2    13372.0  3285.0      923.0  4208.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0        0.0     0.0        0.0     0.0
1    12725.0  4332.0     1103.0  5435.0
2    12514.0  3359.0      687.0  4046.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0        0.0     0.0        0.0     0.0
1    25235.0  7690.0     1790.0  9480.0
2        4.0     1.0        0.0     1.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0        0.0     0.0        0.0     0.0
1    25237.0  7691.0     1790.0  9481.0
2        2.0     0.0        0.0     0.0
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
   decreased  normal  increased      IZ
0        0.0     0.0        0.0     0.0
1    18689.0  5291.0     1070.0  6361.0
2     6550.0  2400.0      720.0  3120.0

In [78]:
#increased = getOccurances('increased',a,0)
#decreased = getOccurances('decreased',a,0)
#normal = getOccurances('normal',a,0)

#print(decreased)
#print(normal)
#print(increased)

feature_ir

,PC-1,PC-2,PC-3,PC-4,PC-5,PC-6,PC-7,PC-8,PC-9
0,0.275243,0.273714,0.272976,0.27317,0.273044,0.27307,0.27307,0.27307,0.27307

In [85]:
def getOccurances(label,data,feature_index):
    labels_counter_array = np.zeros([len(labels)])
    for i in data:
        if(i[feature_index] == label):
            if(i.take(-1) == 'decreased'):
                labels_counter_array[0] += 1
            elif(i.take(-1) == 'normal'):
                labels_counter_array[1] += 1
            elif(i.take(-1) == 'increased'):
                labels_counter_array[2] += 1
    return labels_counter_array

In [47]:
def computeIR(data):
    total_iz = np.sum(data['IZ'].to_numpy())
    total_occurances = np.sum((data.drop(columns=['IZ'])).to_numpy())
    ir = total_iz/total_occurances
    return ir